class ReportGenerator:
    @staticmethod
    def generate_video_report(metadata: dict) -> str:
        lines = []
        lines.append("=" * 34)
        lines.append("VIDEO METADATA REPORT")
        lines.append("=" * 34)
        lines.append("")
        lines.append(f"File Name       : {metadata['file_name']}")
        lines.append(f"File Size       : {metadata['file_size']} bytes")
        lines.append(f"Container       : {metadata['container']}")
        lines.append(f"Duration        : {metadata['duration']} seconds")
        lines.append("")
        lines.append("VIDEO")
        lines.append("-" * 33)
        lines.append(f"Resolution      : {metadata['resolution']}")
        lines.append(f"Frame Rate      : {metadata['frame_rate']}")
        lines.append(f"Bit Rate        : {metadata['bit_rate']}")
        lines.append(f"Codec           : {metadata['codec']}")
        lines.append("")
        lines.append("AUDIO")
        lines.append("-" * 33)
        lines.append(f"Codec           : {metadata['audio_codec']}")
        lines.append(f"Channels        : {metadata['audio_channels']}")
        lines.append(f"Sampling Rate   : {metadata['audio_sampling_rate']}")
        lines.append(f"Bit Rate        : {metadata['audio_bitrate']}")
        lines.append("")
        lines.append("METADATA")
        lines.append("-" * 33)
        lines.append("...")
        lines.append("")
        return "\n".join(lines)
